{
 "title": "NGINX Plus vs Apache Webserver",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Connection Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginxplus_connections_active", "legendFormat": "nginxplus" },
    {
     "expr": "sum(apache_connections{instance=\"f5nginxbenchmarkapache:9117\", state=~\"writing|keepalive|closing\"})",
     "legendFormat": "apache"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (\n  rate(node_cpu_seconds_total{instance=\"f5nginxbenchmarknplus:9100\",mode=\"idle\"}[5m])\n))",
     "legendFormat": "nginxplus"
    },
    {
     "expr": "100 * (1 - avg by(instance) (\n  rate(node_cpu_seconds_total{instance=\"f5nginxbenchmarkapache:9100\",mode=\"idle\"}[5m])\n))",
     "legendFormat": "apache"
    }
   ]
  },
  {
   "title": "Request Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(nginxplus_http_requests_total[5m]))",
     "legendFormat": "nginxplus"
    },
    {
     "expr": "rate(apache_accesses_total[5m])",
     "legendFormat": "apache"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *(1 -  node_memory_MemAvailable_bytes{instance=\"f5nginxbenchmarknplus:9100\"}  /  node_memory_MemTotal_bytes{instance=\"f5nginxbenchmarknplus:9100\"})",
     "legendFormat": "nginxplus"
    },
    {
     "expr": "100 *(1 -  node_memory_MemAvailable_bytes{instance=\"f5nginxbenchmarkapache:9100\"}  /  node_memory_MemTotal_bytes{instance=\"f5nginxbenchmarkapache:9100\"})",
     "legendFormat": "apache"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(up{instance=\"f5nginxbenchmarknplus:9113\"}[5m]) * 100",
     "legendFormat": "nginxplus"
    },
    {
     "expr": "avg_over_time(up{instance=\"f5nginxbenchmarkapache:9117\"}[5m]) * 100",
     "legendFormat": "apache"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "Incoming and outgoing network traffic per interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"f5nginxbenchmarknplus:9100\", device!=\"lo\"}[5m])",
     "legendFormat": "nginxplus"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"f5nginxbenchmarkapache:9100\", device!=\"lo\"}[5m])",
     "legendFormat": "apache"
    }
   ]
  }
 ]
}